version: "3.8"

services:
  web:
    image: nginx
    container_name: web-container
    ports:
      - "8080:80"
    networks:
      - app-network

  alpine:
    image: alpine
    container_name: alpine-container
    command: sleep 3600
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
